### ISSUE TITLE
Work Question

### ISSUE THREAD

**Issue by Buzzzatti** [mav10/react-native-applepay-mir#1]
hi using this library can we add a card to pay via mirpey inside the app ?

**Comment by mav10** [comment]
Hi @Buzzzatti I'm not sure that we are on the one track.

It's absolutely the same thing as you'd have `VISA` or `MasterCard` in your Apple Wallet (native iOS payment method).
So if I understood you correctly - you are talking about NFC tech which is implemented on Android now. But as I know it is not available on iOS native level at all.

With this lib you can pay via MIR card (added to your wallet) in e-stores or apps. Like a you buy something in AppStore and get such View
![image](https://user-images.githubusercontent.com/20200808/209168370-46987111-6b73-4812-a2dd-e46acbaf8597.png)
