### ISSUE TITLE
TypeError: null is not an object (evaluating '_$$_REQUIRE(_dependencyMap[29], "react-native-appay-mir").ApplePay.canMakePayments')

### ISSUE THREAD

**Issue by mohamedhamdy2017** [mav10/react-native-applepay-mir#3]
ApplePay.canMakePayments not working as expected can you please check this ASAP

**Comment by mav10** [comment]
Will check it out

**Comment by mav10** [comment]
It was crazy stuff :) 
Package has not been working since end of 2022. I released version 2.1.3 to NPM

Thanks for catching, unfortunately in my country ApplePay as Batman  - outlaw and not supported, so it's why I didn't noticed it so fast

P.S. close this and #2 issue.
